
const theme = {
  // Landing Site Colors
  navBarText: '#777777',
  navBarTextDark: '#666666',
  landingHeaderBackground: '#ffffff',
  landingHeaderBackgroundDark: '#39434e',
  landingTitleText: '#ff6200',
  landingSubtitleText: '#ffffff',
  landingSubtitleTextDark: '#777777',
  landingTitleFont: '"Exo", sans-serif',
  trialTextColor: '#ffffff',
  overviewTextColor: '#777777',

  // Header colors
  // headerTextColor: '#009fdf',
  headerTextColor: '#ffffff',

  // Footer Colors
  footerItemHeader: '#cccccc',
  footerAddressText: '#aaaaaa',

  // Dashboard Menu
  // dashMenuBackground: '#eeeeee',
  // dashMenuColor: '#777777',
  // dashMenuSelectedBg: '#ffedd4',
  dashMenuBackground: '#39434e',
  // dashMenuColor: '#009fdf',
  dashMenuColor: '#ffffff',
  // dashMenuSelectedBg: '#333333',
  // dashMenuSelectedBg: '#4e5c6b',
  dashMenuSelectedBg: '#39434e',
  dashMenuSelectedBgSettings: '#4e5c6b',
  dashLogoBackground: '#39434e',
  dashMenuSelectedColor: '#029fdf',
  // dashMenuSelectedColor: '#248dff',
  // dashMenuSelectedColor: '#45A8EF',
  // dashMenuSelectedColor: '#ff6200',

  // Filter drop down menus
  filterMenuColor: '#777777',
  filterMenuTitleColor: '#777777',
  filterMenuBorderDark: '#bbbbbb',
  filterMenuBorderLight: '#bbbbbb',
  filterMenuBorderLightest: '#bbbbbb',

  // Role drop down menu
  roleMenuColor: '#777777',
  roleMenuTitleColor: '#eb4f00',
  roleMenuBorderDark: '#333333',
  roleMenuBorderLight: '#777777',

  // Date picker
  calBorderLight: '#bbbbbb',
  calBorderDark: '#bbbbbb',
  calColor: '#777777',
  calColorDark: '#333333',
  calColorInvalid: '#aaaaaa',
  calMonthDisplayBorder: '#cccccc',
  calMonthDisplayTitleColor: '#777777',
  calMonthDisplayDivider: '#777777',
  calSelected: '#ff6200',
  calButtonBg: '#ffedd4',

  // Ad Manager
  admanagerDividerColor: '#dddddd',
  admanagerLabelColor: '#777777',
  admanagerLabelColorLight: 'rgba(119, 119, 119, 0.6)',
  admanagerFormLabelColor: '#ff6200',
  admanagerBorderColor: '#bbbbbb',
  admanagerTabBg: '#eeeeee',
  admanagerTabTextColor: '#ff6200',
  admanagerColumnHeaderBg: '#ff6200',
  admanagerTableSeparator: '#cccccc',
  admanagerTableCellColor: '#777777',
  admanagerTableCellBg: '#eeeeee',
  admanagerLinkColor: '#248dff',
  admanagerBudgetsHeader: '#ff6200',
  admanagerBudgetsText: '#777777',
  admanagerSideBarBg: '#ffedd4',
  admanagerSideBarBorder: '#777777',
  admanagerSideBarSelected: '#ff6200',
  admanagerFormTypeColor: '#777777',
  admanagerClearFilterBorder: '#777777',
  admanagerClearFilterTitleColor: '#ff6200',
  admanagerAutoPilotExclaim: '#ff6200',
  admanagerAutoPilotText: '#777777',
  admanagerStateFormText: '#777777',
  admanagerTableSecondaryLineColor: '#aaaaaa',
  admanagerStateFormLine: '#dddddd',
  admanagerNavButtonColor: '#ff6200',

  // Reports
  reportsMenuTitleColor: '#777777',
  reportsDividerColor: '#dddddd',
  // reportsOuterBg: '#fffaf7',
  reportsOuterBg: '#ffffff',
  reportsBg: '#f8f8f8',
  reportsBorder: '#aaaaaa',
  reportsTabBg: '#eeeeee',
  reportsTabCircleColor: '#777777',
  reportsTabCircleColorLight: '#bbbbbb',
  reportsTabText: '#777777',
  reportsTabTextLight: '#bbbbbb',

  // Tables
  tableTitleColor: '#777777',
  tableValueColor: '#aaaaaa',
  tableCellBorderHighlight: '#ff6200',
  tableCellBorder: '#cccccc',
  tableSelectorOn: '#eb4f00',
  tableSelectorOff: '#777777',

  // Integrations/Settings
  settingsOuterBg: '#ffffff',
  settingsBg: '#f8f8f8',
  settingsBorder: '#aaaaaa',
  settingsHelpColor: '#999999',
  settingsTitleColor: '#777777',
  settingsItemBorder: '#ff6200',
  settingsItemBg: '#cccccc',
  settingsItemBgAlt: '#cccccc',
  settingsLabelColor: '#777777',
  settingsIconOpen: '#ff6200',
  settingsSuccessText: '#ff6200',

  // User Settings
  userOuterBg: '#ffffff',
  userBg: '#f8f8f8',
  userBorder: '#aaaaaa',
  userTitleColor: '#777777',
  userItemBorder: '#eb4f00',
  userItemBg: '#cccccc',
  userItemBgAlt: '#cccccc',
  userIcon: '#555555',
  userIconAdmin: '#ff6200',
  userIconSuperAdmin: '#fedbab',
  userIconNew: '#777777',
  companyAppLabel: '#ff6200',
  billingLabel: '#ff6200',
  billingLabelDark: '#707070',
  billingItem: '#777777',

  // Unregistered
  linkboxBorder: '#777777',

  // Form
  formColor: '#777777',
  formColorDark: '#333333',
  formButtonBg: '#ffedd4',
  formBorderDark: '#333333',
  formBorderMedium: '#aaaaaa',
  formEditButtonColor: '#eb4f00',
  formEditButtonColorLight: '#ff6200',
  formFontSize: '0.65em',
  formRadioBgOn: '#777777',
  formRadioBgOnSelected: '#ff6200',
  formToggleActive: '#ff6200',
  formToggleInactive: '#777777',
  formToggleReadOnly: '#cccccc',

  // SliderInput
  sliderBorder: '#aaaaaa',
  sliderBorderLight: '#ff9533',
  sliderOrange: '#ff6200',

  // Plots
  plotButtonBorder: '#aaaaaa',
  plotButtonColor: '#777777',
  plotButtonOrange: '#eb4f00',

  // Not found page
  notFoundOuterBg: '#fffaf7',
  notFoundBg: '#f8f8f8',
  notFoundBorderLight: '#777777',
  notFoundColor: '#333333',

  brightBlue: '#0bb2ee',
  orange: '#ff6200',
  orangeDark: '#fe3e0a',
  orangeLight: '#ff8f71',
  green: '#56d489',
  reportsBlue: '#327bd1',
  lightBackground: '#f9f9f9',
  darkBackground: '#2a2929',
  darkShadow: '#1d1d1d',
  darkGrey: '#777777',
  dashMenuGrey: '#5a5a5a',
  mediumGrey: '#969696',
  lightGrey: '#999999',
  offWhite: '#eeeeee',
  facebookBlue: '#3b5998',
  googleRed: '#dd4b39',
  amazonYellow: '#ff9900',
  formLineGrey: '#bcbcbc',
  formLineGreyDisabled: '#d7d7d7',
  red: '#d80909',
  font: '"Open Sans", sans-serif',
  fontAlt: "'Helvetica Neue', sans-serif",
  // fontMenu: "'Raleway', sans-serif",
  fontMenu: '"Open Sans", sans-serif',
  borderColor: '#aaaaaa',
};

export default theme;
